#!/usr/bin/env python3
"""Generate architecture/status.generated.c4 from id-registry.json — deterministic,
repo-derived status (no per-run LLM judgment).

Rules (per FQN in "elements"):
  {"fixed": "built|planned|issue"}        -> pinned
  {"file": "rel/path"[, "minBytes": N]}   -> #built if the file exists (and big enough)
  {"glob": "rel/glob"}                    -> #built if any file matches
  {"agent": "name"}                       -> #built if <agentsDir>/name.md exists
  {"skill": "name"[, "minBytes": N]}      -> #built if <skillsDir>/name.md exists (stub=planned)
Stage status (FQN segment before the first dot) is derived from children. Each extend
carries a lastSynced marker. A guard exports the model and FAILS LOUDLY if any status FQN
no longer exists in model.c4 (LikeC4 silently ignores unknown `extend`).

  --if-changed : skip the (slow) export+build when status is unchanged AND the build is
                 fresh. Cheap to run on every Stop hook; only rebuilds on real drift.
"""
import argparse
import glob as globmod
import json
import os
import re
import subprocess
import sys
import tempfile
import time

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
ARCH = os.path.join(ROOT, ".context", "architecture")
REG = os.path.join(HERE, "id-registry.json")
OUT = os.path.join(ARCH, "status.generated.c4")
DIST = os.path.join(ARCH, "dist", "index.html")
MODEL = os.path.join(ARCH, "model.c4")
_LOCAL = os.path.join(ARCH, "node_modules", ".bin", "likec4")
LIKEC4 = [_LOCAL] if os.path.isfile(_LOCAL) else ["npx", "-y", "likec4@1.56.0"]


def evaluate(rule, reg):
    if "fixed" in rule:
        return rule["fixed"]
    if "agent" in rule:
        p = os.path.join(ROOT, reg.get("agentsDir", "claude-config/agents"), rule["agent"] + ".md")
        return "built" if os.path.isfile(p) else "planned"
    if "skill" in rule:
        p = os.path.join(ROOT, reg.get("skillsDir", "claude-config/skills"), rule["skill"] + ".md")
        if not os.path.isfile(p) or ("minBytes" in rule and os.path.getsize(p) < rule["minBytes"]):
            return "planned"
        return "built"
    if "file" in rule:
        p = os.path.join(ROOT, rule["file"])
        if not os.path.isfile(p) or ("minBytes" in rule and os.path.getsize(p) < rule["minBytes"]):
            return "planned"
        return "built"
    if "glob" in rule:
        return "built" if globmod.glob(os.path.join(ROOT, rule["glob"]), recursive=True) else "planned"
    return "planned"


def build_status():
    reg = json.load(open(REG))
    leaf = {fqn: evaluate(rule, reg) for fqn, rule in reg["elements"].items()}
    status = dict(leaf)
    # propagate up to EVERY ancestor level (built if any descendant is built)
    agg = {}
    for fqn, st in leaf.items():
        parts = fqn.split(".")
        for i in range(1, len(parts)):
            agg.setdefault(".".join(parts[:i]), set()).add(st)
    for anc, sts in agg.items():
        if anc not in status:  # never override an explicitly-registered element
            status[anc] = "built" if "built" in sts else ("issue" if sts == {"issue"} else "planned")
    return status


def render(status, ts):
    lines = ["// status.generated.c4 — GENERATED by .context/sync/context-sync.py. DO NOT EDIT.",
             f"// lastSynced: {ts}", "", "model {"]
    for fqn in sorted(status, key=lambda f: (f.count("."), f)):  # parents before children
        lines += [f"  extend {fqn} {{", f"    #{status[fqn]}",
                  f'    metadata {{ lastSynced "{ts}" }}', "  }"]
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--if-changed", action="store_true",
                    help="skip export+build when status unchanged and build is fresh")
    a = ap.parse_args()

    status = build_status()

    # Compare status ignoring timestamps (header + per-element lastSynced) so an unchanged
    # overlay does NOT trigger a rebuild.
    def norm(s):
        s = "\n".join(s.splitlines()[2:])  # drop the 2 header comment lines
        return re.sub(r'lastSynced "[^"]*"', 'lastSynced "TS"', s)

    body_new = norm(render(status, "TS"))
    body_old = norm(open(OUT).read()) if os.path.isfile(OUT) else ""

    fresh = os.path.isfile(DIST) and os.path.getmtime(DIST) >= max(
        os.path.getmtime(MODEL) if os.path.isfile(MODEL) else 0,
        os.path.getmtime(REG) if os.path.isfile(REG) else 0,
    )
    if a.if_changed and body_new == body_old and fresh:
        print("c4 status: no drift — skip")
        return

    ts = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    with open(OUT, "w") as f:
        f.write(render(status, ts))
    counts = {}
    for st in status.values():
        counts[st] = counts.get(st, 0) + 1
    print(f"status.generated.c4: {len(status)} elements -> {counts}")

    tmp = os.path.join(tempfile.gettempdir(), "c4-sync-model.json")
    ex = subprocess.run(LIKEC4 + ["export", "json", "-o", tmp], cwd=ARCH, capture_output=True, text=True)
    if ex.returncode != 0:
        sys.stderr.write((ex.stdout + ex.stderr)[-2500:])
        sys.exit("\nEXPORT FAILED — model.c4 does not parse.")
    model_fqns = set(json.load(open(tmp)).get("elements", {}).keys())
    missing = sorted(f for f in status if f not in model_fqns)
    if missing:
        sys.exit("\nSTALE id-registry — not in model.c4:\n  " + "\n  ".join(missing))
    print(f"guard OK — all {len(status)} FQNs resolve")

    b = subprocess.run(LIKEC4 + ["build", "-o", "dist", "--output-single-file", "--use-hash-history"],
                       cwd=ARCH, capture_output=True, text=True)
    if b.returncode != 0:
        sys.stderr.write((b.stdout + b.stderr)[-2500:])
        sys.exit("\nBUILD FAILED.")
    print("likec4 build OK — overlay applied")


if __name__ == "__main__":
    main()
