// The hosted privacy policy at /privacy — the URL the Chrome Web Store listing points at.
// KEEP IN SYNC with docs/store/PRIVACY_POLICY.md (that file is the source of truth for edits;
// this is its styled, standalone rendering on the product's own domain). Same visual language
// as the share pages (Besley display, ink/purple palette) and, like them, no scripts.

const UPDATED = 'July 8, 2026';

export function renderPrivacyPage(): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1"><title>AI Fluency Index — Privacy policy</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Besley:wght@700;800&display=swap" rel="stylesheet">
<style>
:root{--ink:#17103B;--purple:#5737F4;--muted:#5D5876;--hair:#D9D3EE;--ground:#FBFAFD}
*{box-sizing:border-box}
body{margin:0;min-height:100vh;font:16px/1.65 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:var(--ground);color:var(--ink)}
main{max-width:680px;margin:0 auto;padding:56px 24px 80px}
.brand{font-family:Besley,Georgia,serif;font-weight:800;font-size:15px;letter-spacing:.02em}
h1{font-family:Besley,Georgia,serif;font-weight:800;font-size:clamp(28px,5vw,36px);line-height:1.15;margin:20px 0 4px}
.updated{color:var(--muted);font-size:13.5px;margin-bottom:28px}
h2{font-family:Besley,Georgia,serif;font-weight:700;font-size:19px;margin:34px 0 8px}
p{margin:0 0 14px;color:var(--ink)}
.lead{font-size:17px}
.short{background:#fff;border:1px solid var(--hair);border-left:3px solid var(--purple);border-radius:10px;padding:14px 18px;margin:22px 0}
a{color:var(--purple)}
</style></head><body><main>
<div class="brand">&#9679; AI FLUENCY INDEX</div>
<h1>Privacy policy</h1>
<div class="updated">Last updated: ${UPDATED}</div>

<p class="lead">AI Fluency Index is a browser extension that turns your own AI chat history into an evidence-backed measure of how skillfully you work with AI (four fluency dimensions and a 1-100 score), plus a badge you can choose to share. This policy explains what data the extension touches, where it is processed, and what (little) ever leaves your device.</p>

<div class="short"><b>The short version:</b> your chats are analyzed by the AI provider you already use, inside your own logged-in session. The full result, including verbatim quotes from your chats, stays on your device. Our server only ever receives the distilled badge.</div>

<h2>What data the extension reads</h2>
<p>When you start an analysis from the extension popup, the extension reads your conversation history on the AI provider's own website (claude.ai or chatgpt.com), using the session you are already logged into. It does not read your password, cookies, or anything on other websites, and it does nothing until you click to start a run.</p>

<h2>Where the analysis happens</h2>
<p>The analysis itself runs through your own AI provider. For Claude, the extension runs the inference inside your open claude.ai tab, under your account, in temporary conversations it deletes when the run finishes. For ChatGPT, the extension operates your own logged-in ChatGPT session in background tabs it opens for the run: it sends the analysis prompts, reads the replies, and deletes the temporary conversations afterwards, so nothing is left in your ChatGPT history. In both cases the analysis starts only when you click to run it, and the only party that processes your raw chats is the provider that already holds them. Your chats are never sent to us or to any other third party.</p>

<h2>What stays on your device</h2>
<p>The full result is stored locally in your browser's extension storage. This includes your four fluency assessments and score, the verbatim chat quotes that back each of them, and a small pool of previously verified quotes that keeps your score stable between runs. The quotes exist so you can audit every claim against its evidence. They never leave your device.</p>

<h2>What is sent to our server</h2>
<p>If you sync or share, the extension sends the distilled badge to our server (aibadges-api.mindmaterial.io): your fluency score, level, the four dimension bands, and opaque evidence identifiers that can only be resolved on your device. The quote text is stripped in code before anything is sent, and this boundary is covered by automated tests. Each provider (Claude, ChatGPT) syncs under its own random key generated by the extension, so each gets its own share page; we do not ask for your name or email.</p>

<h2>Sharing</h2>
<p>Your badge is private by default. If you mark it public, we create a share page for it at a link you control. Only the content you chose to surface appears on that page. You can switch it back to private at any time from the extension.</p>

<h2>What we never collect</h2>
<p>We do not collect your raw conversations, chat quotes, browsing history, or credentials. The extension contains no analytics, advertising, or tracking code, and we do not sell or share data with anyone.</p>

<h2>Data retention and deletion</h2>
<p>Local data is yours: removing the extension (or clearing its storage from the extension's settings) deletes the result and all evidence from your device. To delete the badge data held on our server, use "Delete my server data" at the bottom of the extension's results page. It removes everything we store for you, including any share links, immediately. You can also email us at the address below and we will remove it for you.</p>

<h2>Security</h2>
<p>All traffic to our server uses HTTPS. Server-side data is limited to the distilled badge described above, keyed by a random identifier rather than your identity.</p>

<h2>Changes to this policy</h2>
<p>If we change what data the extension touches or transmits, we will update this policy, and the version of the extension that introduces the change will say so in its release notes.</p>

<h2>Contact</h2>
<p>Questions or deletion requests: <a href="mailto:sebastian@privado.id">sebastian@privado.id</a></p>
</main></body></html>`;
}
